name: neilalexander.dev
title: neilalexander.dev
#url: "https://neilalexander.dev"

include: [".well-known", "xrpc"]

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-redirect-from

#theme: jekyll-theme-minimal
#baseurl: "/"

defaults:
  -
    scope:
      path:            "_posts/*.md"
    values:
      sitemap:         true

feed:
  tags:
    except:
      - tag-to-exclude
      - another-tag
